---
title: "Datasets"
author: "M. Jan, P. Franken"
date: '`r Sys.Date()`'
output:
  html_document:
    code_folding: show
    df_print: paged
    fig_caption: yes
    highlight: pygments
    number_sections: no
    theme: sandstone
    toc: yes
    toc_depth: 4
    rows.print: 6
    toc_float: yes
  pdf_document:
    fig_caption: yes
  word_document:
    toc: yes
    toc_depth: '4'
---

Figure for publication

Presenting dataset of mouse and human

# LIBS

```{r}
library(patchwork)
library(dplyr)
source("../FileLocation.R")
source(RASTERPLOT_FUN)
source(TEMPLATE_FUN)
source(COLORFUN)
colorCode<-ColorCode()
```


# Plot

load data 

```{r}
dataMouse<-LOADMOUSE(Tissue="Cortex")
dataHuman<-LOADHUMAN()
```



Plot Mouse data

```{r,fig.width=3,fig.height=6}
#Plot Mouse, empty data
ggM<-RasterPlot(ProbeGene = "Ncor1",Dataset = "Cortex",npretty = 2,MeanPointSize = 0,AddCISegment = F,ModelFitLine = 0,DaysShows =c(1,2,3,4,5,10),BSL_RepLine = 0,AddASkeldonSol = F,PreviousHourShow = 8,ylim=c(0,.1),AddSleepWake = T)
ggM<-ggM+annotate("line",x=c(26,26),y=c(-2,0),size=1)
ggM<-ggM+annotate("text",label="BSL",x=27,y=-1,hjust=0,fontface = "bold")

ggM<-ggM+annotate("line",x=c(26,26),y=c(-3,-2),size=1,color="red")
ggM<-ggM+annotate("text",label="SD",x=27,y=-2.5,hjust=0,color="red",fontface = "bold")+theme(plot.margin = margin(2,45,2,2),axis.title.y = element_blank())

# Add RNA-seq points
cortex_sample<-cbind.data.frame(Time=unique(dataMouse$rna_expr$Time),value=0.25)
cortex_sample<-ProcessDataRaster(cortex_sample,"value",DoReplicate = F)

liver_sample<-cbind.data.frame(Time=unique(dataMouse$rna_expr$Time),value=0.05)
liver_sample<-ProcessDataRaster(liver_sample,"value",DoReplicate = F)

ggM<-ggM+annotate("point",x=cortex_sample$ZT,y=cortex_sample$value,fill=colorCode[["Cortex"]],color="black",shape=21,size=3)
ggM<-ggM+annotate("point",x=liver_sample$ZT,y=liver_sample$value,fill=colorCode[["Liver"]],color="black",shape=21,size=3)

ggM
```

Desynchronization

```{r,fig.width=3,fig.height=6}
ggHD<-RasterPlot(ProbeGene = "A_23_P211899",Dataset = "Desync",npretty = 2,MeanPointSize = 0,AddCISegment = F,ModelFitLine = 0,DaysShows =seq(1,11),BSL_RepLine = 0,AddASkeldonSol = F,PreviousHourShow = 8,ylim=c(0,2),AddSleepWake = T)
ggHD<-ggHD+theme(plot.margin = margin(0,50,2,2),axis.title.y = element_blank())


ggHD<-ggHD+annotate("line",x=c(26,26),y=c(-2,-1),size=1)
ggHD<-ggHD+annotate("text",label="BSL",x=27,y=-1.5,hjust=0,fontface = "bold")

ggHD<-ggHD+annotate("line",x=c(26,26),y=c(-10,-2),size=1,color="red")
ggHD<-ggHD+annotate("text",label="anti-\nphase",x=27,y=-5.5,hjust=0,color="red",fontface = "bold")
ggHD<-ggHD+annotate("text",label="in-\nphase",x=27,y=-2.5,hjust=0,color="red",fontface = "bold")
ggHD<-ggHD+annotate("text",label="in-\nphase",x=27,y=-9.5,hjust=0,color="red",fontface = "bold")


# Add RNA-seq points
HD_sample<-cbind.data.frame(Time=unique(dataHuman$HT_Desync$Time),value=0.25)
HD_sample<-ProcessDataRaster(HD_sample,"value",DoReplicate = F)

ggHD<-ggHD+annotate("point",x=HD_sample$ZT,y=HD_sample$value,fill=colorCode[["Blood"]],color="black",shape=21,size=3)

ggHD
```



Ctr

```{r,fig.width=3,fig.height=6}
ggHC<-RasterPlot(ProbeGene = "A_23_P211899",Dataset = "Ctr",npretty = 2,MeanPointSize = 0,AddCISegment = F,ModelFitLine = 0,DaysShows =seq(1,11),BSL_RepLine = 0,AddASkeldonSol = F,PreviousHourShow = 8,ylim=c(0,1),AddSleepWake = T)
ggHC<-ggHC+theme(plot.margin = margin(0,50,2,2),axis.title.y = element_blank())

ggHC<-ggHC+annotate("line",x=c(26,26),y=c(-2,-1),size=1)
ggHC<-ggHC+annotate("text",label="BSL",x=27,y=-1.5,hjust=0,fontface = "bold")

ggHC<-ggHC+annotate("line",x=c(26,26),y=c(-9,-2),size=1,color="black",linetype="solid")
ggHC<-ggHC+annotate("text",label="10h\nsleep",x=27,y=-5.5,hjust=0,color="black",fontface = "bold")

ggHC<-ggHC+annotate("line",x=c(26,26),y=c(-10,-9),size=1,color="red",linetype="solid")
ggHC<-ggHC+annotate("text",label="CR",x=27,y=-9.5,hjust=0,color="red",fontface = "bold")


# Add RNA-seq points
HC_sample<-cbind.data.frame(Time=unique(dataHuman$HT_Ext$Time),value=0.25)
HC_sample<-ProcessDataRaster(HC_sample,"value",DoReplicate = F)

ggHC<-ggHC+annotate("point",x=HC_sample$ZT,y=HC_sample$value,fill=colorCode[["Blood"]],color="black",shape=21,size=3)

ggHC
```

restricted

```{r,fig.width=3,fig.height=6}
ggHR<-RasterPlot(ProbeGene = "A_23_P211899",Dataset = "Res",npretty = 2,MeanPointSize = 0,AddCISegment = F,ModelFitLine = 0,DaysShows =seq(1,11),BSL_RepLine = 0,AddASkeldonSol = F,PreviousHourShow = 8,ylim=c(0,1),AddSleepWake = T)
ggHR<-ggHR+theme(plot.margin = margin(0,50,2,2),axis.title.y = element_blank())

ggHR<-ggHR+annotate("line",x=c(26,26),y=c(-2,-1),size=1)
ggHR<-ggHR+annotate("text",label="BSL",x=27,y=-1.5,hjust=0,fontface = "bold")

ggHR<-ggHR+annotate("line",x=c(26,26),y=c(-9,-2),size=1,color="black",linetype="solid")
ggHR<-ggHR+annotate("text",label="6h\nsleep",x=27,y=-5.5,hjust=0,color="black",fontface = "bold")

ggHR<-ggHR+annotate("line",x=c(26,26),y=c(-10,-9),size=1,color="red",linetype="solid")
ggHR<-ggHR+annotate("text",label="CR",x=27,y=-9.5,hjust=0,color="red",fontface = "bold")


# Add RNA-seq points
HR_sample<-cbind.data.frame(Time=unique(dataHuman$HT_Res$Time),value=0.25)
HR_sample<-ProcessDataRaster(HR_sample,"value",DoReplicate = F)

ggHR<-ggHR+annotate("point",x=HR_sample$ZT,y=HR_sample$value,fill=colorCode[["Blood"]],color="black",shape=21,size=3)

ggHR
```

Melatonin

```{r}
ggmel<-RasterPlot(ProbeGene = "A_23_P211899",Dataset = "Res",npretty = 2,MeanPointSize = 0,AddCISegment = F,ModelFitLine = 0,DaysShows =1,BSL_RepLine = 0,AddASkeldonSol = F,PreviousHourShow = 8,ylim=c(0,1),AddFits = list(list(time=seq(-8,24,by=.1),y1=0.5+0.5*sin(2*pi/24*seq(-8,24,by=.1)+(2*pi/24*2)))),LtyAddFits = "solid",ColsAddFits = colorCode[["SCNforce"]])

ggmel<-ggmel+theme(axis.title = element_blank(),axis.text = element_blank(),axis.ticks = element_blank())
```


```{r,fig.width=10,fig.height=6}
#ggM+ggtitle("[Mus Musculus]\nSD")|((ggmel+ggtitle("[Human]\nDesynchronization"))/ggHD)|((ggmel+ggtitle("[Human]\nC.R. after control"))/ggHC)|((ggmel+ggtitle("[Human]\nC.R. after restricted sleep"))/ggHR)

p1<-ggM+ggtitle("Mouse - SD")+ theme(axis.text = element_text(size = 14),axis.title = element_text(size = 14))    
#p2<-ggmel+ggtitle("Human - FD")
p3<-ggHD+ggtitle("Human - FD")+ theme(axis.text = element_text(size = 14),axis.title = element_text(size = 14))    
#p4<-ggmel+ggtitle("Human - 10h sleep + CR")
p5<-ggHC+ggtitle("Human - 10h sleep + CR")+ theme(axis.text = element_text(size = 14),axis.title = element_text(size = 14))    
#p6<-ggmel+ggtitle("Human - 6h sleep + CR")
p7<-ggHR+ggtitle("Human - 6h sleep + CR")+ theme(axis.text = element_text(size = 14),axis.title = element_text(size = 14))    


# layout <- "
# ABDF
# ACEG
# "

layout <- "
ABCD
"

#ggF<-p1 + p2 + p3 + p4 + p5+ p6 + p7 + 
#  plot_layout(design = layout,heights = c(1,11))

ggF<-p1 + p3 + p5 + p7 + 
  plot_layout(design = layout)

ggF

ggsave(paste(FIGUREDIR,"Datasets.pdf",sep=""), width = 200*1.2, height = 150*1.2, units = "mm",plot = ggF)
ggsave(paste(FIGUREDIR,"Datasets.png",sep=""), width = 200*1.2, height = 150*1.2, units = "mm",plot = ggF)
```



# Linear plots

```{r,fig.width=6,fig.height=3}
source(LINEARPLOT_FUN)
#Plot Mouse, empty data
ggM<-LinearPlot(ProbeGene = "Ncor1",Dataset = "Cortex",npretty = 2,MeanPointSize = 0,AddCISegment = F,ModelFitLine = 0,DaysShows =c(1,2,3,4,5,10),BSL_RepLine = 0,AddASkeldonSol = F,ylim=c(0,1.2),AddSleepWake = T,ScaleSW = F)+
  
  coord_cartesian(ylim=c(0,1.2),clip = "off",expand = F)+theme(plot.margin =  margin(t = 20, r = 0, b =10, l = 0, unit = "pt"),
      axis.text.x = element_text(angle = 45, vjust = 1, hjust=1),
      axis.text = element_text(size = 12))+scale_y_continuous(breaks=seq(0,1,by=.25))+ylab("Wake fraction")

ggM<-ggM+annotate("line",x=c(0,48),y=c(1.25,1.25),size=.5)
ggM<-ggM+annotate("text",label="BSL",x=24,y=1.3,vjust=0,fontface = "bold")
# 
ggM<-ggM+annotate("line",x=c(48,54),y=c(1.25,1.25),size=.5,color="red")
ggM<-ggM+annotate("text",label="SD",x=51,y=1.3,vjust=0,color="red",fontface = "bold")

ggM<-ggM+annotate("line",x=c(54,240),y=c(1.25,1.25),size=.5,color="black")
ggM<-ggM+annotate("text",label="REC",x=96,y=1.3,vjust=0,color="black",fontface = "bold")

# 
# # Add RNA-seq points
cortex_sample<-cbind.data.frame(Time=unique(dataMouse$rna_expr$Time),value=.35)

# 
liver_sample<-cbind.data.frame(Time=unique(dataMouse$rna_expr$Time),value=0.15)

# 
ggM<-ggM+annotate("point",x=cortex_sample$Time,y=cortex_sample$value,fill=colorCode[["Cortex"]],color="black",shape=21,size=1.5)
ggM<-ggM+annotate("point",x=liver_sample$Time,y=liver_sample$value,fill=colorCode[["Liver"]],color="black",shape=21,size=1.5)
# 
ggM
```

Desynchronization

```{r,fig.width=6,fig.height=3}
ggHD<-LinearPlot(ProbeGene = "A_23_P211899",Dataset = "Desync",npretty = 2,MeanPointSize = 0,AddCISegment = F,ModelFitLine = 0,DaysShows =seq(1,11),BSL_RepLine = 0,AddASkeldonSol = F,ylim=c(0,1.2),AddSleepWake = T,ScaleSW = F)+
  
  coord_cartesian(ylim=c(0,1.2),clip = "off",expand = F)+theme(plot.margin =  margin(t = 20, r = 0, b = 10, l = 0, unit = "pt"),
      axis.text.x = element_text(angle = 45, vjust = 1, hjust=1),
      axis.text = element_text(size = 12))+scale_y_continuous(breaks=seq(0,1,by=.25))+ylab("Wake fraction")

ggHD<-ggHD+annotate("line",x=c(0,48),y=c(1.25,1.25),size=.5)
ggHD<-ggHD+annotate("text",label="BSL",x=24,y=1.3,vjust=0,fontface = "bold")
# 
ggHD<-ggHD+annotate("line",x=c(48,228),y=c(1.25,1.25),size=.5,color="red")
ggHD<-ggHD+annotate("text",label="in-phase",x=48,y=1.3,vjust=0,hjust=0,color="red",fontface = "bold")

ggHD<-ggHD+annotate("text",label="anti-phase",x=120,y=1.3,vjust=0,hjust=0,color="red",fontface = "bold")
ggHD<-ggHD+annotate("text",label="in-phase",x=216 ,y=1.3,vjust=0,hjust=0,color="red",fontface = "bold")
# 
# 
# # Add RNA-seq points
HD_sample<-cbind.data.frame(Time=unique(dataHuman$HT_Desync$Time),value=0.25)
# 
ggHD<-ggHD+annotate("point",x=HD_sample$Time,y=HD_sample$value,fill=colorCode[["Blood"]],color="black",shape=21,size=1.5)

ggHD
```


add melatonin data

```{r}
library(dplyr)
library(circular)
load(HUMANFD_CIRCADIANINFO_RDATA)
load(HUMANFD_SLEEP_RDATA)

#  # Melatonin onset information
# Lights out: L-> D , we consider this as CT0

# Add phase degree at start recording 
metaDSW<-metaDSW %>% left_join(Desync_Circa_Meta,by=c("Subj"="subj","SP"="sp"))

# Get phase degree when lights out
library(lubridate)
idx<-metaDSW$SP == 1
DiffTime<-hm(metaDSW$Lights.out.time[idx])-hms(metaDSW$Start.recording.time[idx])
DiffInH<-hour(DiffTime)+minute(DiffTime)/60+second(DiffTime)/3600
DiffInH[DiffInH< -12]<- DiffInH[DiffInH< -12] %% 24

# DiffInH =  Difference Start recording and light out
PhaseDegree_LightsOut<-(metaDSW[idx,]$Phase.degree.at.Start.recording + 360/metaDSW[idx,]$Tau*DiffInH) %% 360
PhaseRad_Lightsout<-PhaseDegree_LightsOut*pi/180#2*pi/metaDSW[idx,]$Tau*(metaDSW[idx,]$Tau/360*PhaseDegree_LightsOut)

PhaseInfo<-cbind.data.frame(Rad=PhaseRad_Lightsout,Period=metaDSW[idx,]$Tau,subj=metaDSW[idx,]$Subj)
rownames(PhaseInfo)<-PhaseInfo$subj

MeanMelatoninPhase<-mean.circular(PhaseInfo$Rad)[[1]]
MeanPeriod<-mean(PhaseInfo$Period)
  
ggHD<-ggHD+annotate("line",x=seq(0,220),y=0.25+0.25*sin(2*pi/MeanPeriod*seq(0,220)+MeanMelatoninPhase),color=colorCode[["SCNforce"]])

# for (i in rownames(PhaseInfo)){
#   ggHD<-ggHD+annotate("line",x=seq(0,220),y=0.25+0.25*sin(2*pi/PhaseInfo[i,]$Period*seq(0,220)+PhaseInfo[i,]$Rad),color=colorCode[["SCNforce"]],linetype="22")
# }
```




```{r,fig.width=6,fig.height=3}
ggHC<-LinearPlot(ProbeGene = "A_23_P211899",Dataset = "Ctr",npretty = 2,MeanPointSize = 0,AddCISegment = F,ModelFitLine = 0,DaysShows =seq(1,11),BSL_RepLine = 0,AddASkeldonSol = F,ylim=c(0,1.2),AddSleepWake = T,ScaleSW = F)+
  
  coord_cartesian(ylim=c(0,1.2),clip = "off",expand = F)+theme(plot.margin =  margin(t = 20, r = 0, b = 10, l = 0, unit = "pt"),
      axis.text.x = element_text(angle = 45, vjust = 1, hjust=1),
      axis.text = element_text(size = 12))+scale_y_continuous(breaks=seq(0,1,by=.25))+ylab("Wake fraction")

ggHC<-ggHC+annotate("line",x=c(0,48),y=c(1.25,1.25),size=.5)
ggHC<-ggHC+annotate("text",label="BSL",x=24,y=1.3,vjust=0,hjust=0,fontface = "bold")
# 
ggHC<-ggHC+annotate("line",x=c(48,216),y=c(1.25,1.25),size=.5,color="black",linetype="solid")
ggHC<-ggHC+annotate("text",label="10h sleep",x=48,y=1.3,vjust=0,hjust=0,color="black",fontface = "bold")
# 
ggHC<-ggHC+annotate("line",x=c(202,240),y=c(1.25,1.25),size=.5,color="red",linetype="solid")
ggHC<-ggHC+annotate("text",label="CR",x=216,y=1.3,vjust=0,hjust=0,color="red",fontface = "bold")
# 
# 
# # Add RNA-seq points
HC_sample<-cbind.data.frame(Time=unique(dataHuman$HT_Ext$Time),value=0.25)

# 
ggHC<-ggHC+annotate("point",x=HC_sample$Time,y=HC_sample$value,fill=colorCode[["Blood"]],color="black",shape=21,size=1.5)

ggHC
```


restricted

```{r,fig.width=6,fig.height=3}
ggHR<-LinearPlot(ProbeGene = "A_23_P211899",Dataset = "Res",npretty = 2,MeanPointSize = 0,AddCISegment = F,ModelFitLine = 0,DaysShows =seq(1,11),BSL_RepLine = 0,AddASkeldonSol = F,ylim=c(0,1.2),AddSleepWake = T,ScaleSW = F)+
  
  coord_cartesian(ylim=c(0,1.2),clip = "off",expand = F)+theme(plot.margin =  margin(t = 20, r = 0, b = 10, l = 0, unit = "pt"),
      axis.text.x = element_text(angle = 45, vjust = 1, hjust=1),
      axis.text = element_text(size = 12))+scale_y_continuous(breaks=seq(0,1,by=.25))+ylab("Wake fraction")

ggHR<-ggHR+annotate("line",x=c(0,48),y=c(1.25,1.25),size=.5)
ggHR<-ggHR+annotate("text",label="BSL",x=24,y=1.3,vjust=0,hjust=0,fontface = "bold")
# 
ggHR<-ggHR+annotate("line",x=c(48,216),y=c(1.25,1.25),size=.5,color="black",linetype="solid")
ggHR<-ggHR+annotate("text",label="6h sleep",x=48,y=1.3,vjust=0,hjust=0,color="black",fontface = "bold")
# 
ggHR<-ggHR+annotate("line",x=c(200,240),y=c(1.25,1.25),size=.5,color="red",linetype="solid")
ggHR<-ggHR+annotate("text",label="CR",x=216,y=1.3,vjust=0,hjust=0,color="red",fontface = "bold")
# 
# 
# # Add RNA-seq points
HC_sample<-cbind.data.frame(Time=unique(dataHuman$HT_Res$Time),value=0.25)

# 
ggHR<-ggHR+annotate("point",x=HC_sample$Time,y=HC_sample$value,fill=colorCode[["Blood"]],color="black",shape=21,size=1.5)

ggHR
```


```{r,fig.width=6,fig.height=10}
#ggM+ggtitle("[Mus Musculus]\nSD")|((ggmel+ggtitle("[Human]\nDesynchronization"))/ggHD)|((ggmel+ggtitle("[Human]\nC.R. after control"))/ggHC)|((ggmel+ggtitle("[Human]\nC.R. after restricted sleep"))/ggHR)

p1<-ggM+ggtitle("Mouse - SD")+ theme(axis.text = element_text(size = 12),axis.title = element_text(size = 12),plot.title = element_text(vjust = 4))+scale_y_continuous(breaks=c(0,.5,1)) 
#p2<-ggmel+ggtitle("Human - FD")
p3<-ggHD+ggtitle("Human - FD")+ theme(axis.text = element_text(size = 12),axis.title = element_text(size = 12),plot.title = element_text(vjust = 4))+scale_y_continuous(breaks=c(0,.5,1))    
#p4<-ggmel+ggtitle("Human - 10h sleep + CR")
p5<-ggHC+ggtitle("Human - 10h sleep + CR")+ theme(axis.text = element_text(size = 12),axis.title = element_text(size = 12),plot.title = element_text(vjust = 4))+scale_y_continuous(breaks=c(0,.5,1))    
#p6<-ggmel+ggtitle("Human - 6h sleep + CR")
p7<-ggHR+ggtitle("Human - 6h sleep + CR")+ theme(axis.text = element_text(size = 12),axis.title = element_text(size = 12),plot.title = element_text(vjust = 4))+scale_y_continuous(breaks=c(0,.5,1))    


# layout <- "
# ABDF
# ACEG
# "

layout <- "
A
B
C
D
"

#ggF<-p1 + p2 + p3 + p4 + p5+ p6 + p7 + 
#  plot_layout(design = layout,heights = c(1,11))

ggF<-p1 + RemoveXaxis(p3) + RemoveXaxis(p5) + p7 + 
  plot_layout(design = layout)

ggF

ggsave(paste(FIGUREDIR,"DatasetsLinear.pdf",sep=""), width = 156*1, height = 150*1, units = "mm",plot = ggF)
ggsave(paste(FIGUREDIR,"DatasetsLinear.png",sep=""), width = 156*1, height = 150*1, units = "mm",plot = ggF)

#, width = 125*1.5, height = 150*1.5, units = "mm",plot = ggF
```



```{r}
sessionInfo()
```

